name: 1. Preprocessing Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'survey_lung_cancer_raw.csv'
      - 'preprocessing/automate_Rifzki.py'
      - '.github/workflows/preprocessing.yml'

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      # Menjalankan skrip dari root direktori
      - name: Run preprocessing script
        run: python preprocessing/automate_Rifzki.py